# For PoC purpose only.
# Will be moved to https://github.com/kubernetes-sigs/krew-index after hnc has it's release.
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: hierarchical-namespaces
spec:
  shortDescription: Manipulates hierarchical namespaces.
  description: |
    Manipulates hierarchical namespaces provided by the Hierarchical Namespace Controller (HNC).
  version: --- will be populated by make krew-build ---
  homepage: https://github.com/kubernetes-sigs/multi-tenancy/incubator/hnc
  platforms:
    - uri: https://github.com/example/foo/releases/v1.0.tar.gz
      selector:
        matchLabels:
          os: linux
          arch: amd64
      sha256: --- will be populated by make krew-build ---
      files:
        - from: "bin/kubectl/kubectl-hns"
          to: "."
      bin: "./kubectl-hns"
